language: ruby
jdk:
- oraclejdk8
rvm:
- 2.3.1
node_js:
- v6.10.3
before_install:
- openssl aes-256-cbc -K $encrypted_dca3c32be0a4_key -iv $encrypted_dca3c32be0a4_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
- chmod 600 ../deploy
- eval `ssh-agent -s` && ssh-add ../deploy
- cp etc/settings.xml $HOME/.m2/settings.xml
install:
- nvm install v6.10.3
- nvm use v6.10.3
- npm install -g yarn
- yarn install
- rvm use 2.3.1
- gem install bundler
- bundle install
script: bundle exec buildr ci
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: NngAM/AQ4LCEHLoghWhj+eQ/HCDfF6j1wDh1eMtG4Nrv83MU+wNJ3KZSJOOswNO8SmQjQnfvMhx07IbSU0w6nB1URHajgDm7Zt7vBxcITL+Ah9T7pJURykYTZ6rdcGopMWdy8Wy+EfKYbchPMlDHXyE2k46xXJBI9wMNG9Xm/ssu40Zvv42eP9EfffXyENtdgJRcZP5P9DUb9wWDJVi64vFap9oI6G/r8jxg07OOjZAwqV2PcZ7TAtkQBs+NbTdPFrB2iNf04G1wsh2GJlFpghFcd6R/lkKGOdkRwfZ18BCaS2Gq6fHCeIJll0xtXEwCdElFLJHJ7eumolU47ZmGV0oHwlYfVgeOSjk/QGlc1+KQB2K/e8nwCZ7wm+M4L8UaCCFOcr/d4p90h3cKgdATC/3ltxoYvq/YUGYKkaVkezwiV/GUtDrkSU3y6FG7A8tinIWKtmUqL3iSppQMP8TlPAOc7jEbCcj/7VW8e+GvKmoW65AsMGYW5vEGXN8OGdiNHCdWzblUtJNCWamUJfTnXpKk5Z/iyMLkvIiU71bcp7m7rph1eztICqtX4e9kJTml3dhkBs+Ss58Sk1HeaQRXdBZp0ZpGHPpK7rQpWgbRpWaYcxhaCLT4LBesOTtIylqSPJ31DnpuvuD+LxPwbrxQCbTANl3PtAlYbjRMZzsanTY=
  - secure: c1LObJ3Msfp6Yu4jx0+sFvt5SY4/7B9hq5+cK7t3aTEugFC3D430OhqSm3itPQ/ZBVUl8YUNsM0/QRhdy4SK5gLFTy0UO1JzsX6keJ66zKtT9GBinopOewrzI/o7zqkYtutqZ6p32TX0HYq5sk506EtUoZrCSlUKfgbmTH9Zx68XMHm9LTuk9BoKzaTPJdiSGkqxbNQkLMpjZdsjOndJi3BVzvRSDw5GkMERroxKcnlaG2lqnOI15zXOgdB0fEiCIVrwOIAtDEvIs7aLz5S+bZ04TGkWjsO3rJChXahCbRA3qAIS+2mD9wnGQWUNH9aFld2O3HzqlJsuGNHZWMfng2v5te/nAxXutAuUjFFFUi/xJNp7207KsBvC1ovc6ZmUyXCfejGcw9LVMpw4KtRXZZKKF5WikfdMdxyvS4C05cecGKmbnoxD9v45dEBfV4nHN+EdmPznw9ajXtBXo8cKdAt4IH3SVEGAUz14B8wHxwMHpEkjJp3jmYHt27hPEWhTLjYvOjcRg1k1X8ZSZaB+5+bxSJE4avp+NTSMm3vE4eDrzU0SkNxRIa+91SwlLyVBvWhoLcSglYFOgE1B5o7BUvKKNAARawrhqn7ZCF5UAMEEyS0Zf+9fEdPZ8tuVH5MFvv8KZi12j3YnWVu1NTrg1WYEHELaeN1ouVI9hOekAWk=
  - secure: t3AAlF8qkI0CPVAfWfVimmdiYdT1X5fS7D8Y97I9F97BPBuhD7U1wmCUF496MyUxuWUdXfd6xe26f4fL57t6/BHwASxb70vTYPhq2jVNTvSG6RUlVqbX6GgTWe2X9Ahfu5ynGT0KDcH2rCQX27/8IngXXGxhDdaTbXAAr0riUlbLmL4X//1JU2BydHKswIEKHSz0Dpvi/ZacX1hOMYNWqxQZy2zgz3ttr4otT/g1SjkfTYjfNIP22znv8Qhhh2iLtFPdhUVlp0e3WSOl2Rrc3wa3rGX6rzZViQ+0tuMIqrTAOdjQPfNHuOvdA31rJ5eLiMe+L1SrNoIZTYOh3gbDH5RPNuJDEupYwyFYO+yfQVMe4ZRvAwyhovY/Z3etM6MH8y9DyPSjHMV2qsoOB92o1zbs91zFNxbLg87xl3SCuboTOWnu1GzYTk/Vb204Ky+uNOXHUyi/UGvk7S/uKZeGCkpY3pMyUIZYjSMOBiIRa/IJesYidH5B3mUsDhQSNlrT7nUiyTzVEcFIldmYW2SZ41RRVX1AfOLZ4uR4R19pc+qJM2UpcMdN0E7tKHjc2v3zhIEdrv8PZoKMznVWwgICvjKRrm8arOuJvO6PY3dKJYuZ81WrOxE1FJwFoiao+TChAVC18Dvqr9sz3RfJBNqMlNf4s7HknDAWsz8aO3bXt6I=
  - secure: uuOu1jMBarj7NwMcaV2UKvzmzRec0y08OUpEs5pxwLAsREn6n+8OUQ4tuiolfMs+Df14nYOGaFelAbixbc4Kf8DlmUvV6hlBXprBaSfXkM1REicewUrQ/mLW/3qSp2cVV5Gx3du9ASTFFWDps61kOd2x17aUbTjOKXWLRiZHKhkWIh3cADG/kNgAwNKFKPy3upTuoX6V7c4qk3NPD5mAcNcWng6gEJaQyRvK+sHm3fLuJ1/xg+76RAF2uLw1iVRMpAuvoTDxWziizvpFXSYxPrNCu+Q5IPJ5ST4lfroJt6Idi4jefKlNc9671nO+pfgXml3VGOlI3eT7FiTH2yYvkYJWbz9dkHW3dUosW1hT/OkXU4s9FjFjr6mDCiePL6uvOmKUZmEgcnEo6RlJTu9mTwYxei8X6+RT9D6iz7Q8sYiNIS+Zk3oMciYPSukts4rJRQjedAwnPNDUIeafEexmAMjrXqI9dpRj6PTeqB6lQrw3rfouHXW6tCZ/PwqTIPXGdgg0zN0cIdfauKnldxYF+z1r/2Hcm6upYI1GCZmqRsDPJSXmurDNOhSg88iYPCcAk6uqJIU0bjukpCFG4kv1axIcHneHces2ZswUbwV3AHPsrWS6McFH6IRW+YFMOOBkxwW43Ke885cFuMBKxXVG6+AV56At/QeVkSHe02ABsKc=
  - secure: Qwq2Q65fHiDHof4zDxTki3Qn9s8qCmXzXSIV8QHt4zwgqWlvqHifJChlZJ7VCqq82FZ34uQAc85Z+cw2Wxmw+r1gLgqb1bEHLttwFAyFN7SA/68uVM24Evh4x1i4gTtjyxH9qHTljLlJUWpp+hqS7hBKtry2kDTw3xe48G2u7VdiprlfYVwFfuWfCkbecF7fCnREW4skMR/PhenGMmZYoFOonJb2E/0udQcp/gkZ9SHj67UgWq5H9WY6EuIVrCfcBxVyNY9iCInQaXnHZYOYeM/4m/xqnCpP5f/oKdt889kcY8xZyvJjpd8uB6THkwSQWVn+H6lBaog7WkgWU3n3vor5rBM2FwRuN+VzXMmAU1P7MJRjnY3deHX2QjkYzjTWhnbW9H7FJ3v2Vd2Svhfasj2YTpNJEzaFksZv5QmDaQ9YFs3iiBiKOxls0o1jL99rua/vuj5xUybTddUoaNg2Q/CHMm7g1BT2IC4tBG0cUTRBZ+xIJNRkwVLFsnLcw+FczJ2uEuRA7txZeXPErhlSCmudn65tbOzcY76AuDrfZwPzQ4p22iniUaHGsbpo1QH5/qGm5IabGmZAw+5pdWlfiLPfxpHXxSWAk1vg/qQyuE1SWqOMQKYinHBAt/7nN++K/H44H3WwyfxYzh/m6pwl9bY5XMgQC/7+nrr6D8jkmAU=
