language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
node_js:
- v6.10.3
before_install:
- openssl aes-256-cbc -K $encrypted_dca3c32be0a4_key -iv $encrypted_dca3c32be0a4_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
- chmod 600 ../deploy
- eval `ssh-agent -s` && ssh-add ../deploy
install:
- nvm install v6.10.3
- nvm use v6.10.3
- npm install -g yarn
- yarn install
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr package jacoco:report site:deploy publish_if_tagged
after_success:
  - bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: DymiZuDTzwfY+H35p5sh0QON6lEO7Agp3wSH1UAyMBmdnaFd/Q/iuDrKDnuMrlwoP0dO5xpRtuHIW2HAuuaY5RtZUsIFA9mMADu3vVh2FVAC16G7ZKfj333M/rQc6WgGH50UjFvzpun+L+IwjXKtkxqSenAc/f6smNGlN9hyvqjKiWHWN+PgTgpNcKFsKt/o7QfQY5m4m1mt7ztH+YGMhLUKpscfiZSw8Sjw9MwlXIbM7kRH5ezsw5f3oDr0eUcqsG0MqmYKh6a05Pf7CC3AfhAoMY6yHG9CaWxVBlohcCC7bsE3BwEVhBcLOFk1HPCa2LxfKOHzwZZu0l1h63CcIvKQr5qZQIWhe3VlnDdBZz8IUTP89Fm9zk1NcC/m4JlNQbouob6ZsiO5Ew3/3jFnAfUfVZ41mjo8TFpvI9r6FnuS9iYSQKQi/WDE5DyRSnftjH+I+ywut852Fcw39y2MgA1/4ZZx/uxlOChH88xncR7tccqMBGSfy1+pDrlabBKqtTEBI6DmXU6DgbfBOinvquwaShydPdet9zpTKckhT7/zydhFlinvO2m+4G2MVd8H83XW7F/02xf0s/gfNQuEZBau7IoKw+TIozHUr37tTrhF5FbLQOz7JoFksZcgbFsVivW5193KAssE83gW8pIRFgN1JIAhCrFPvZ/6PlkHkOk=
  - secure: Slkr65mgAflU+WWSVt17JoncJuWlfMry/ET/YtTm6E/6jxvDnL/tqEymBFZtbLPHsWAtNPd7HbvnVogjyOrlUvSz8FEek3S6S9sNOedSzUNIfArZMa2c3eNzub+9xCYRIZK1fDI2swvty3RhnQCrLXLy6DOmLwDZ1wEeEWGlbm0FkgBXqOutaqpSIFvVrNXNHfuLZCkJI4ok/XTBijJYr45phaLUhsi4LtnnXohkdn1le47P3LHKkxtlT6qJWr2PEDEsl+0oC4vq0Df8+5IJFUN6OdxTBAcbyw1K5Tj89sLQheDfOXui2pSZwSyWh9DHgRoAw0UW35EnUtlWXwZ0UUjxRDz/mm+8Xs58kYyPzC8rpkZu3LPudm7+mxKWm3zK6VNWIXJibkV8TPI0hkEVWCyR67CvMDxYwC7X6uoc7O9Yd752ogVkhJkrR16bizmXLpHfmgpIo6YnUTq9fyj8G5blobAx3TEll1AaXjcVTHaGeB5uq5NEKQDafwIsPe9BUGH7uN0FBT62Nzgy6SnsA9TU+vtRntcuVtDx/gutgY1dQRr7qYMFNKm9IMDtOm+tk4j+6CnIiun0mjy6XDRqK01AyJgR7U8bvRCnhL8Mx911aT3SXa3IGlh61FLvd8q+nPTqaobjyu1SnB7QujInhFxEoRh9MqBNiIrSyOQPkPE=
  - secure: I6v83KNjwkwnTBFHledc5qFRY1R531WW0wDe2aJC2nU/iXDzESEMUtACDJlizfOktBqAK+TdtCLU/251PC61oA8faXvrC1aXb3a6W4t9dK/RjkEgPf+CxWtbjos3uSLsNHtbqiwddYUNpxhJypi0S2737koDIa85zyx0doVE/+lJjxDgFESsCM1ttkfVED5iGhUElP7RY2qx8orfDA6kI6D3H3vlLYtzUY6MbMtdDhbCWBUFPrUraiyLhbWaxu80hL9jLPhtYOSJ/ayMM+zxUDv4euptnw9w/eZ0NIIHDyCPJTpPRs97XWpGCPRWSKCekCgCyJBS0GKAjpCGtslSerR+3PJmBWS08DFvOepQW9AcHaLpsVreTkWx7gRuLNE4FePJZa8dAFlI6FORR0pELZF3RFBQqXN6W0He+vr0nWQAC7WeAOa0vcno97dwOhnO46t2xihF80ITmEM9LFnHmVHDI91R6Xfp5d6v4oJ/dCdqxo2/uyxkz6ih0gyP1cuZsbdqpH1wau3v0EDqbpM1jpEo2Y+HBpWUlj/nbc5Dkv/fDwzSL2rjH96u0hIKUj53fUTejc/NOqZN6Cow2jHkd//oxJnM+GIEOsexpFV+Kg+rsHeg84sZ1SK1FP2pdrTLG6aNpBHVsF/R83d19wlgOssKUtWFw6Xfzs769ttEh1I=
  - secure: qZagu8vy63A23YSx7k1iiZlG3GPK3zi2NRJjmAnGoYi2Sfg6vIaxira8Wvm95xfnAOQ+YciuIZGZex+insXodORA9/UsGqxMiqIr5gcESDZRgzO+Q5xJx5DzNIPYNC3jUg8H4YAS8jypfUxQ/kp8AbWkUNjtqhnwY9aCsGr/Zbm2lgEB1/xPPgnTkJThY9X5kU5KNOfnQlIf3/PPML7c059Fc6Jhcu2QGgprImE0Zx1id2FImCae7yaWn0sbMwPgzebCo71k8I8mq3F+/1cQKEgeIzbWaWXWMYZ1Amjv/Cv1hb+psGXFKHjDK5CVWTmzBmFLURkU0ziNcSW+SeOSNgTUl0u02TJUZ2jy1P7cw62B4fOe2511KHXmMinhGpVM82OZRYbkxWczrgYj8LsDXSo6wqQwgIHHiUmorfOXOUdOmEejuiP93J/jbFbNfGeuOMSbKwRV+3n02ucpLn07BcEjC1wZ7mmXoyOdG5+vHjAbUqPwq0U2UCgrteBVPgQxIr86iW9o6bj/8WyHks8GuZif0ToXGtWK7E95zM+oK7Y4l+iZEFO8gbLRXo8iEQDd4wMUtYY8lzFfhGpwRWF94o57TyXvqMuRtxMA36KW6xggmoonUkVq9g+SckJI1Rz9mI63jxDsYTyD+NP9EFc5jpZViGpvYLe4m4wBs5AiBEM=
  - secure: jGz41ev29hHMAnVLuA1QDWergD0BYBzqqdUAeeuPQuw0rgT2dpcJ0TqY+beKcTNeQ/qvzxku0063tzF4HMvnlyWqK17JGmm4b4ubQKfosZWcDw8YlemwzofteuujBI5ZhFwoY7TFczAwI5mYBs4eYkSGd9i3iLFe3yEkm410qaVdLz7KdReimJJMOItafhixtBif94uukO5T9zlnuDmYhii+/bbhzoayLAc2iWm6Wen8b+Fx9coda9CdJ9ZlxmUvYLO2Mm5+RcfuNBtXhXVc2oxvWQoC97mIacwp6CpgvEBjqUHO78FaMlTUFfEHGkWxfV7uEEwp0Q0r9KTXbt8yTgt8ZvSg2MbE3xZ/WZ9ACzYNXVK3bQTEQKa3IMUDlX+SdErOxcm4wkPNadBNH0s8SYitaJVpCuZ6+SCsp6Uoc+CywV46ImihebxWgz8Wh0oRQnO/XGtpTPnkCB8K146z5vsZ+ECwSEukxF9KOyk1ylLFuCtsQuVDoOZhxrvKC8zt6+JAsMEawDtiVoznOs6Tt3kQ9SyJjPxmFyiiY6OrJskyzaZdTq+lOQPG4tbX3Txq4vnRI+lWcTMgkV6CK1Iv69mKkVVY/pJnUDPTysyp5GqvBVmXT16t+pGeFO7GF02UBOF0/z7TW/61di9G8LFpss5htDBKpQt4AI/YCArjiYE=
