language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
node_js:
- v6.10.3
before_install:
- openssl aes-256-cbc -K $encrypted_dca3c32be0a4_key -iv $encrypted_dca3c32be0a4_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
- chmod 600 ../deploy
- eval `ssh-agent -s` && ssh-add ../deploy
install:
- nvm install v6.10.3
- nvm use v6.10.3
- npm install -g yarn
- yarn install
- rvm use 2.3.1
- gem install bundler
- bundle install
script: bundle exec buildr package jacoco:report site:deploy mcrt:publish_if_tagged
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: NngAM/AQ4LCEHLoghWhj+eQ/HCDfF6j1wDh1eMtG4Nrv83MU+wNJ3KZSJOOswNO8SmQjQnfvMhx07IbSU0w6nB1URHajgDm7Zt7vBxcITL+Ah9T7pJURykYTZ6rdcGopMWdy8Wy+EfKYbchPMlDHXyE2k46xXJBI9wMNG9Xm/ssu40Zvv42eP9EfffXyENtdgJRcZP5P9DUb9wWDJVi64vFap9oI6G/r8jxg07OOjZAwqV2PcZ7TAtkQBs+NbTdPFrB2iNf04G1wsh2GJlFpghFcd6R/lkKGOdkRwfZ18BCaS2Gq6fHCeIJll0xtXEwCdElFLJHJ7eumolU47ZmGV0oHwlYfVgeOSjk/QGlc1+KQB2K/e8nwCZ7wm+M4L8UaCCFOcr/d4p90h3cKgdATC/3ltxoYvq/YUGYKkaVkezwiV/GUtDrkSU3y6FG7A8tinIWKtmUqL3iSppQMP8TlPAOc7jEbCcj/7VW8e+GvKmoW65AsMGYW5vEGXN8OGdiNHCdWzblUtJNCWamUJfTnXpKk5Z/iyMLkvIiU71bcp7m7rph1eztICqtX4e9kJTml3dhkBs+Ss58Sk1HeaQRXdBZp0ZpGHPpK7rQpWgbRpWaYcxhaCLT4LBesOTtIylqSPJ31DnpuvuD+LxPwbrxQCbTANl3PtAlYbjRMZzsanTY=
  - secure: c1LObJ3Msfp6Yu4jx0+sFvt5SY4/7B9hq5+cK7t3aTEugFC3D430OhqSm3itPQ/ZBVUl8YUNsM0/QRhdy4SK5gLFTy0UO1JzsX6keJ66zKtT9GBinopOewrzI/o7zqkYtutqZ6p32TX0HYq5sk506EtUoZrCSlUKfgbmTH9Zx68XMHm9LTuk9BoKzaTPJdiSGkqxbNQkLMpjZdsjOndJi3BVzvRSDw5GkMERroxKcnlaG2lqnOI15zXOgdB0fEiCIVrwOIAtDEvIs7aLz5S+bZ04TGkWjsO3rJChXahCbRA3qAIS+2mD9wnGQWUNH9aFld2O3HzqlJsuGNHZWMfng2v5te/nAxXutAuUjFFFUi/xJNp7207KsBvC1ovc6ZmUyXCfejGcw9LVMpw4KtRXZZKKF5WikfdMdxyvS4C05cecGKmbnoxD9v45dEBfV4nHN+EdmPznw9ajXtBXo8cKdAt4IH3SVEGAUz14B8wHxwMHpEkjJp3jmYHt27hPEWhTLjYvOjcRg1k1X8ZSZaB+5+bxSJE4avp+NTSMm3vE4eDrzU0SkNxRIa+91SwlLyVBvWhoLcSglYFOgE1B5o7BUvKKNAARawrhqn7ZCF5UAMEEyS0Zf+9fEdPZ8tuVH5MFvv8KZi12j3YnWVu1NTrg1WYEHELaeN1ouVI9hOekAWk=
  - secure: t3AAlF8qkI0CPVAfWfVimmdiYdT1X5fS7D8Y97I9F97BPBuhD7U1wmCUF496MyUxuWUdXfd6xe26f4fL57t6/BHwASxb70vTYPhq2jVNTvSG6RUlVqbX6GgTWe2X9Ahfu5ynGT0KDcH2rCQX27/8IngXXGxhDdaTbXAAr0riUlbLmL4X//1JU2BydHKswIEKHSz0Dpvi/ZacX1hOMYNWqxQZy2zgz3ttr4otT/g1SjkfTYjfNIP22znv8Qhhh2iLtFPdhUVlp0e3WSOl2Rrc3wa3rGX6rzZViQ+0tuMIqrTAOdjQPfNHuOvdA31rJ5eLiMe+L1SrNoIZTYOh3gbDH5RPNuJDEupYwyFYO+yfQVMe4ZRvAwyhovY/Z3etM6MH8y9DyPSjHMV2qsoOB92o1zbs91zFNxbLg87xl3SCuboTOWnu1GzYTk/Vb204Ky+uNOXHUyi/UGvk7S/uKZeGCkpY3pMyUIZYjSMOBiIRa/IJesYidH5B3mUsDhQSNlrT7nUiyTzVEcFIldmYW2SZ41RRVX1AfOLZ4uR4R19pc+qJM2UpcMdN0E7tKHjc2v3zhIEdrv8PZoKMznVWwgICvjKRrm8arOuJvO6PY3dKJYuZ81WrOxE1FJwFoiao+TChAVC18Dvqr9sz3RfJBNqMlNf4s7HknDAWsz8aO3bXt6I=
  - secure: dJhKjIwADNsvTV9Ri2gS/zLMyDVP8ojWT6m1KC6mYS6V/sQLZgfwds8FxKumk3PZBeiULeo0ThBNfE06UukQnrrxk6pHI9C9nkpaQJkqkI8H1lLV7XiSJooUMiUsxvYlnr4riDVJZbWDrt0QoKXZQ7K9avlHnyApuA1tL0OO/96AOirXBDAOELO3wFkmNKQRWyQ84KVkEjKwx8SBRucr19t+V314272gu87r37yAlOJ4z4En5BHibVtDMSykxB17YqG9CqZIq3/qO6UvyWEc4AjOdpwKctT3ydkNfABXlFUTIWUuS2OFs9lVG9vV0ewClE+gXCaGNVBnvai/r4Gl1c7TIYNXZx6RedYvbSyZLZnmYVTFQMjcaf5onJN0CzOXu7bN38/oJ9cFLTDHNHYL8RNZQ/mZchNpxkOXPbAB1ylw/7TlnAfRkPBYHJW4MymfJbBbJ4Spr9lTL6nhs6GoafE3MHx4jhq6CSKLOBQva433AaMwYl27bqZdytcnW6W3k4gD6QLeLpC5LMOHyWXLhBGv5yMJj30c7tXUcTLzQ6MHoyVX3KY2g8Tq3ZH5rEoxV0T7Jq4cNoUrMwUhUy3bNCUcsj7HwA8SfmLkxKGzwOEahgugV1WB/Jqc5PKoH4PfYpya0gITqnevX2hlLXxilR+vatZEzx50KGHyg6s4+jg=
  - secure: VL385Y8IRQJEOUl/5QdCDarbODvfx+kLY7KUWNtkMJ2hl9L02OQumCi0+HHCXgL9qbNP741lF7w5j4QXICGrnsBpuUWQxPFmvLNlKk6tZvlExPt1VLefiSYwir/Tmn3tx4lbHXro5ssj09dS+M2/fWHqniJEtasQGQGf/i/OR8c5UYyS7hUk/G1ICowSSHOxd84fX9e4j5hOSxLhKMfgqlOTnZr5x1adFaKEhf/YupGzbU9NKKu4bfSKL2r64fMJUBeGuSGP+g5Q2Wis7IK957664e1SuY/kGvZvjYxYM3PPKm7go4MXEY1i42tRHYdKcwI3AKXWrzRQomxfyY/URt695Ezc3su8SC2/IIpMW+URyS1q5YQl9BZFb8bkty0V7gnFNZz8oTxQBM1nVIJ3tWcJmIneWC1zNmPCKyTO9A7li/f5OwIN8LeW39H2H31La3df0dN8AJ5Lc06wz3Rkfv+KjTynrPqEA9FERFeJutA2Hqr4rPQn7wFcGWOh0zVIvAfw4qmdp5SWqffP1MpJF2u7OU/hiMAIoLdbA8Ey03xWDy0puIFTDtOtrQPcrqt0GFRAD12ZaeyfdSCqmPgF9fJzBX7vXVwT4waKvNNqiLb2Emsjc1yzAWBKKoGaliCkxRc/ppOsOR64TKE9t3NWGrbAk9LgcyaXfN2Jjcrbq60=
