repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.9

  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.1
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  gwt_interop_utils: com.github.gwtreact:gwt-interop-utils:jar:0.4.0
  react: com.github.gwtreact:gwt-react:jar:0.6.0
  react_router: com.github.gwtreact:gwt-react-router:jar:0.5.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.1

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.1
  jsinterop_annotations_sources: com.google.jsinterop:jsinterop-annotations:jar:sources:1.0.1

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-beta-1
  jsinterop_base_sources: com.google.jsinterop:base:jar:sources:1.0.0-beta-1

  elemental2_core: com.google.elemental2:elemental2-core:jar:1.0.0-beta-1
  elemental2_dom: com.google.elemental2:elemental2-dom:jar:1.0.0-beta-1
  elemental2_promise: com.google.elemental2:elemental2-promise:jar:1.0.0-beta-1

  javapoet: com.squareup:javapoet:jar:1.7.0
  guava: com.google.guava:guava:jar:21.0
  arez_annotations: org.realityforge.arez:arez-annotations:jar:gwt:X
  arez_core: org.realityforge.arez:arez-core:jar:gwt:X
  arez_processor: org.realityforge.arez:arez-processor:jar:X
  arez_extras: org.realityforge.arez:arez-extras:jar:gwt:X
  arez_browser_extras: org.realityforge.arez:arez-browser-extras:jar:gwt:X
